# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32883768500a6c8919a6691cbd682d210ac0a5bf73481903a92b4ec92d6e3ae8086d4c8d3911cac352ab0214176d7559baffffd279d638fbdede0bb55d828c1b

test:
  secret_key_base: 36ba5971b7d8f686831b5c725c789ecadc991bff314e78773adaa4ca957029dca93d9fbb8f302378946e7008c7582eafc03f23c755b333380be29441c243a4b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
